<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>33BB54A2-3924-4D79-994C-6CF4580D2F93.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <Authors>Brazil</Authors>
    <AssemblyVersion>1.0</AssemblyVersion>
    <FileVersion>1.0</FileVersion>
    <AssemblyName>DAT1-GUI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\background.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="33BB54A2-3924-4D79-994C-6CF4580D2F93.ico" />
    <Resource Include="Resources\background.jpg" />
  </ItemGroup>

  <ItemGroup>
    <!-- kept because used in ConfigEditorWindow.xaml.cs -->
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="IronPython" Version="3.4.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <!-- only simpleicons is used for github icon in WelcomeWindow.xaml -->
    <PackageReference Include="MahApps.Metro.IconPacks.SimpleIcons" Version="5.1.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Pfim" Version="0.11.3" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAT1\DAT1.csproj" />
    <ProjectReference Include="..\OverstrikeShared\OverstrikeShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="DownloadVgmstreamCli" AfterTargets="Build">
    <PropertyGroup>
      <VgmstreamDir>$(OutDir)3rdparty</VgmstreamDir>
      <VgmstreamExe>$(VgmstreamDir)\vgmstream-cli.exe</VgmstreamExe>
      <VgmstreamZip>$(VgmstreamDir)\vgmstream-win.zip</VgmstreamZip>
      <VgmstreamUrl>https://github.com/vgmstream/vgmstream/releases/latest/download/vgmstream-win.zip</VgmstreamUrl>
    </PropertyGroup>
    <Exec Command="powershell -Command &quot;if (!(Test-Path '$(VgmstreamDir)')) { New-Item -ItemType Directory -Path '$(VgmstreamDir)' }&quot;" />
    <Exec Condition="!Exists('$(VgmstreamExe)')" Command="powershell -Command &quot;Invoke-WebRequest -Uri '$(VgmstreamUrl)' -OutFile '$(VgmstreamZip)'&quot;" />
    <Exec Condition="!Exists('$(VgmstreamExe)') and Exists('$(VgmstreamZip)')" Command="powershell -Command &quot;Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('$(VgmstreamZip)', '$(VgmstreamDir)')&quot;" />
    <Exec Condition="Exists('$(VgmstreamZip)')" Command="del /f /q &quot;$(VgmstreamZip)&quot;" />
  </Target>

</Project>
